<?php

namespace Fuel\Migrations;

use Fuel\Core\DBUtil;

class Create_Tables
{

	private $tables = [
		/**
		 * 利用者テーブル
		 */
		'customers'			 => [
			'id'						 => ['type' => 'bigint', 'auto_increment' => true, 'unsigned' => true, 'comment' => '内部ID'],
			'created_at'				 => ['type' => 'datetime', 'null' => true, 'comment' => '作成日時'],
			'updated_at'				 => ['type' => 'datetime', 'null' => true, 'comment' => '更新日時'],
			'deleted_at'				 => ['type' => 'datetime', 'null' => true, 'comment' => '削除日時'],
			'created_user_id'			 => ['type' => 'int', 'null' => true, 'comment' => '作成スタッフID'],
			'updated_user_id'			 => ['type' => 'int', 'null' => true, 'comment' => '更新スタッフID'],
			'family_name'				 => ['type' => 'varchar', 'constraint' => 20, 'comment' => 'お名前（姓）'],
			'given_name'				 => ['type' => 'varchar', 'constraint' => 20, 'comment' => 'お名前（名）'],
			'family_name_kana'			 => ['type' => 'varchar', 'constraint' => 40, 'null' => true, 'comment' => 'カナ（姓）'],
			'given_name_kana'			 => ['type' => 'varchar', 'constraint' => 40, 'null' => true, 'comment' => 'カナ（名）'],
			'post_code'					 => ['type' => 'varchar', 'constraint' => 50, 'null' => true, 'comment' => '郵便番号'],
			'address'					 => ['type' => 'varchar', 'constraint' => 255, 'null' => true, 'comment' => '住所'],
			'blood_type'				 => ['type' => 'varchar', 'constraint' => 2, 'null' => true, 'comment' => '血液型'],
			'birthday'					 => ['type' => 'date', 'null' => true, 'comment' => '生年月日'],
			'height'					 => ['type' => 'decimal', 'constraint' => '4,1', 'null' => true, 'comment' => '身長'],
			'weight'					 => ['type' => 'decimal', 'constraint' => '4,1', 'null' => true, 'comment' => '体重'],
			'temperature'				 => ['type' => 'decimal', 'constraint' => '4,1', 'null' => true, 'comment' => '体温'],
			'blood_pressure_systolic'	 => ['type' => 'decimal', 'constraint' => '4,1', 'null' => true, 'comment' => '最高血圧'],
			'blood_pressure_diastolic'	 => ['type' => 'decimal', 'constraint' => '4,1', 'null' => true, 'comment' => '最低血圧'],
			'phone_number_1'			 => ['type' => 'varchar', 'constraint' => 50, 'null' => true, 'comment' => '電話番号1'],
			'phone_number_2'			 => ['type' => 'varchar', 'constraint' => 50, 'null' => true, 'comment' => '電話番号2'],
			'twilio_number'				 => ['type' => 'varchar', 'constraint' => 50, 'null' => true, 'comment' => 'twilio番号'],
			'twilio_client'				 => ['type' => 'varchar', 'constraint' => 50, 'null' => true, 'comment' => 'twilioクライアント名'],
			'email'						 => ['type' => 'varchar', 'constraint' => 255, 'null' => true, 'comment' => 'メールアドレス'],
			'share_email_1'				 => ['type' => 'varchar', 'constraint' => 255, 'null' => true, 'comment' => '共有メールアドレス'],
			'share_email_2'				 => ['type' => 'varchar', 'constraint' => 255, 'null' => true, 'comment' => '共有メールアドレス'],
			'share_email_3'				 => ['type' => 'varchar', 'constraint' => 255, 'null' => true, 'comment' => '共有メールアドレス'],
			'share_email_4'				 => ['type' => 'varchar', 'constraint' => 255, 'null' => true, 'comment' => '共有メールアドレス'],
			'share_email_5'				 => ['type' => 'varchar', 'constraint' => 255, 'null' => true, 'comment' => '共有メールアドレス'],
			'note'						 => ['type' => 'text', 'null' => true, 'comment' => 'メモ'],
			'photo'						 => ['type' => 'varchar', 'constraint' => 255, 'null' => true, 'comment' => '顔写真'],
			'gcm_push_token'			 => ['type' => 'varchar', 'constraint' => 255, 'null' => true, 'comment' => 'GCMプッシュトークン'],
			'is_connected'				 => ['type' => 'tinyint', 'unsigned' => true, 'default' => 0, 'null' => true, 'comment' => '端末接続状態'],
		],
		/**
		 * スタッフテーブル
		 */
		'staffs'			 => [
			'id'				 => ['type' => 'bigint', 'auto_increment' => true, 'unsigned' => true, 'comment' => '内部ID'],
			'created_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '作成日時'],
			'updated_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '更新日時'],
			'deleted_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '削除日時'],
			'created_user_id'	 => ['type' => 'int', 'null' => true, 'comment' => '作成スタッフID'],
			'updated_user_id'	 => ['type' => 'int', 'null' => true, 'comment' => '更新スタッフID'],
			'login_id'			 => ['type' => 'varchar', 'constraint' => 50, 'comment' => 'ログインID'],
			'password'			 => ['type' => 'varchar', 'constraint' => 255, 'comment' => 'パスワード'],
			'family_name'		 => ['type' => 'varchar', 'constraint' => 20, 'comment' => '氏名（姓）'],
			'given_name'		 => ['type' => 'varchar', 'constraint' => 20, 'comment' => '氏名（名）'],
			'family_name_kana'	 => ['type' => 'varchar', 'constraint' => 40, 'null' => true, 'comment' => 'カナ（姓）'],
			'given_name_kana'	 => ['type' => 'varchar', 'constraint' => 40, 'null' => true, 'comment' => 'カナ（名）'],
			'email'				 => ['type' => 'varchar', 'constraint' => 255, 'null' => true, 'comment' => 'メールアドレス'],
			'phone_number'		 => ['type' => 'varchar', 'constraint' => 50, 'null' => true, 'comment' => '電話番号'],
			'login_hash'		 => ['type' => 'varchar', 'constraint' => 100, 'null' => true, 'comment' => 'ログインハッシュ'],
			'logined_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '最終ログイン日時'],
		],
		/**
		 * 聞き取りテーブル
		 */
		'hearings'			 => [
			'id'				 => ['type' => 'bigint', 'auto_increment' => true, 'unsigned' => true, 'comment' => '内部ID'],
			'created_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '作成日時'],
			'updated_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '更新日時'],
			'deleted_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '削除日時'],
			'created_user_id'	 => ['type' => 'int', 'null' => true, 'comment' => '作成スタッフID'],
			'updated_user_id'	 => ['type' => 'int', 'null' => true, 'comment' => '更新スタッフID'],
			'customer_id'		 => ['type' => 'bigint', 'unsigned' => true, 'comment' => '利用者ID'],
			'hearing_at'		 => ['type' => 'date', 'null' => true, 'comment' => '聞き取り日'],
			'hearing_content'	 => ['type' => 'longtext', 'null' => true, 'comment' => '聞き取り内容']
		],
		/**
		 * 関係者テーブル
		 */
		'customer_relations' => [
			'id'				 => ['type' => 'bigint', 'auto_increment' => true, 'unsigned' => true, 'comment' => '内部ID'],
			'created_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '作成日時'],
			'updated_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '更新日時'],
			'deleted_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '削除日時'],
			'created_user_id'	 => ['type' => 'int', 'null' => true, 'comment' => '作成スタッフID'],
			'updated_user_id'	 => ['type' => 'int', 'null' => true, 'comment' => '更新スタッフID'],
			'customer_id'		 => ['type' => 'bigint', 'unsigned' => true, 'null' => true, 'comment' => '利用者ID'],
			'family_name'		 => ['type' => 'varchar', 'constraint' => 20, 'comment' => 'お名前（姓）'],
			'given_name'		 => ['type' => 'varchar', 'constraint' => 20, 'comment' => 'お名前（名）'],
			'family_name_kana'	 => ['type' => 'varchar', 'constraint' => 40, 'null' => true, 'comment' => 'カナ（姓）'],
			'given_name_kana'	 => ['type' => 'varchar', 'constraint' => 40, 'null' => true, 'comment' => 'カナ（名）'],
			'relation'			 => ['type' => 'varchar', 'constraint' => 50, 'null' => true, 'comment' => '続柄'],
			'post_code'			 => ['type' => 'varchar', 'constraint' => 7, 'null' => true, 'comment' => '郵便番号'],
			'address'			 => ['type' => 'varchar', 'constraint' => 255, 'null' => true, 'comment' => '住所'],
			'birthday'			 => ['type' => 'date', 'null' => true, 'comment' => '生年月日'],
			'phone_number_1'	 => ['type' => 'varchar', 'constraint' => 50, 'null' => true, 'comment' => '電話番号1'],
			'phone_number_2'	 => ['type' => 'varchar', 'constraint' => 50, 'null' => true, 'comment' => '電話番号2'],
			'email'				 => ['type' => 'varchar', 'constraint' => 256, 'null' => true, 'comment' => 'メールアドレス'],
			'is_emergency'		 => ['type' => 'tinyint', 'unsigned' => true, 'default' => 0, 'comment' => '緊急発信対象フラグ'],
			'emergency_order'	 => ['type' => 'tinyint', 'unsigned' => true, 'default' => 0, 'comment' => '緊急発信優先順位'],
		],
		/**
		 * 関係者共有テーブル
		 */
		'customer_shares' => [
			'id'				 => ['type' => 'bigint', 'auto_increment' => true, 'unsigned' => true, 'comment' => '内部ID'],
			'created_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '作成日時'],
			'updated_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '更新日時'],
			'deleted_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '削除日時'],
			'created_user_id'	 => ['type' => 'int', 'null' => true, 'comment' => '作成スタッフID'],
			'updated_user_id'	 => ['type' => 'int', 'null' => true, 'comment' => '更新スタッフID'],
			'customer_id'		 => ['type' => 'bigint', 'unsigned' => true, 'null' => true, 'comment' => '利用者ID'],
			'hash'				 => ['type' => 'varchar', 'constraint' => 100, 'comment' => 'ハッシュ'],
			'password'			 => ['type' => 'varchar', 'constraint' => 255, 'comment' => 'パスワード'],
			'logined_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '最終ログイン日時'],
		],
		/**
		 * Twilio履歴
		 */
		'twilio_histories'	 => [
			'id'				 => ['type' => 'bigint', 'auto_increment' => true, 'unsigned' => true, 'comment' => '内部ID'],
			'created_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '作成日時'],
			'updated_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '更新日時'],
			'deleted_at'		 => ['type' => 'datetime', 'null' => true, 'comment' => '削除日時'],
			'created_user_id'	 => ['type' => 'int', 'null' => true, 'comment' => '作成スタッフID'],
			'updated_user_id'	 => ['type' => 'int', 'null' => true, 'comment' => '更新スタッフID'],
			'staff_id'			 => ['type' => 'bigint', 'unsigned' => true, 'null' => true, 'comment' => 'スタッフID'],
			'customer_id'		 => ['type' => 'bigint', 'unsigned' => true, 'null' => true, 'comment' => '利用者ID'],
			'to'				 => ['type' => 'varchar', 'constraint' => 50, 'null' => true, 'comment' => '接続先'],
			'from'				 => ['type' => 'varchar', 'constraint' => 50, 'null' => true, 'comment' => '発信元'],
			'record_file_path'	 => ['type' => 'text', 'null' => true, 'comment' => '録音ファイルパス'],
			'sid'				 => ['type' => 'varchar', 'constraint' => 34, 'null' => true, 'comment' => 'セッションid'],
			'parent_call_sid'	 => ['type' => 'varchar', 'constraint' => 34, 'null' => true, 'comment' => '通話id'],
			'account_sid'		 => ['type' => 'text', 'null' => true, 'comment' => 'アカウントid'],
			'status'			 => ['type' => 'varchar', 'constraint' => 20, 'null' => true, 'comment' => '状態'],
			'start_time'		 => ['type' => 'datetime', 'null' => true, 'comment' => '通話開始日時'],
			'end_time'			 => ['type' => 'datetime', 'null' => true, 'comment' => '通話終了日時'],
			'duration'			 => ['type' => 'int', 'null' => true, 'comment' => '通話時間'],
			'price'				 => ['type' => 'float', 'null' => true, 'comment' => '通話料金'],
		],
		'meals'				 => [
			'id'								 => ['type' => 'bigint', 'auto_increment' => true, 'unsigned' => true],
			'created_at'						 => ['type' => 'datetime', 'null' => true],
			'updated_at'						 => ['type' => 'datetime', 'null' => true],
			'deleted_at'						 => ['type' => 'datetime', 'null' => true],
			'name'								 => ['type' => 'varchar', 'constraint' => 100, 'null' => true],
			'kana'								 => ['type' => 'varchar', 'constraint' => 100, 'null' => true],
			'category_menu'						 => ['type' => 'varchar', 'constraint' => 100, 'null' => true],
			'category_cooking'					 => ['type' => 'varchar', 'constraint' => 100, 'null' => true],
			'category_cuisine'					 => ['type' => 'varchar', 'constraint' => 100, 'null' => true],
			'category_chief_material'			 => ['type' => 'varchar', 'constraint' => 100, 'null' => true],
			'adequate_intake'					 => ['type' => 'varchar', 'constraint' => 100, 'null' => true],
			'amount'							 => ['type' => 'smallint', 'unsigned' => true],
			'energy'							 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'moisture'							 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'protein'							 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'lipid'								 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'carbohydrate'						 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'calcium'							 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'iron'								 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'vitamin_A'							 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'vitamin_D'							 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'vitamin_B1'						 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'vitamin_B2'						 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'vitamin_C'							 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'saturated_fatty_acid'				 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'monovalent_saturated_fatty_acid'	 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'polyvalent_saturated_fatty_acid'	 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'dietary_fiber'						 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'salt'								 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'menu_staple_food'					 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'menu_side_dish'					 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'menu_main_dishes'					 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'menu_milk'							 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'menu_fruit'						 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'menu_confectionery'				 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'cereal'							 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'also_attached_much'				 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'sugar_sweeteners_such'				 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'nuts_and_seeds'					 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'green_and_yellow_vegetables'		 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'other_vegetables'					 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'fruits'							 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'mushrooms'							 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'seaweed'							 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'beans'								 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'seafood'							 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'meat'								 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'eggs'								 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'milks'								 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'oils_and_fats'						 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'confectionery'						 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'taste_beverages'					 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'seasonings_and_spices'				 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'other'								 => ['type' => 'float', 'constraint' => '7,2', 'null' => true],
			'is_temporary'						 => ['type' => 'tinyint', 'unsigned' => true, 'default' => 0],
		],
//        'customer_profiles'		 => [
//            'id'						 => ['type' => 'bigint', 'auto_increment' => true, 'unsigned' => true],
//            'created_at'				 => ['type' => 'datetime', 'null' => true],
//            'updated_at'				 => ['type' => 'datetime', 'null' => true],
//            'deleted_at'				 => ['type' => 'datetime', 'null' => true],
//            'customer_id'				 => ['type' => 'bigint', 'unsigned' => true, 'null' => true],
//            'input_date'				 => ['type' => 'date'],
//            'height'					 => ['type' => 'tinyint', 'unsigned' => true],
//            'weight'					 => ['type' => 'tinyint', 'unsigned' => true],
//            'bmi'						 => ['type' => 'tinyint', 'unsigned' => true],
//            'max_blood_pressure'		 => ['type' => 'smallint', 'unsigned' => true],
//            'min_blood_pressure'		 => ['type' => 'smallint', 'unsigned' => true],
//            'midarm_circumference'		 => ['type' => 'tinyint', 'unsigned' => true],
//            'triceps_skinfold_thickness' => ['type' => 'tinyint', 'unsigned' => true],
//            'midarm_muscle_area'		 => ['type' => 'tinyint', 'unsigned' => true],
//            'calf_circumference'		 => ['type' => 'tinyint', 'unsigned' => true],
//            'family_structure'			 => ['type' => 'text', 'null' => true],
//            'question1'					 => ['type' => 'text', 'null' => true],
//            'question2'					 => ['type' => 'text', 'null' => true],
//            'question3'					 => ['type' => 'text', 'null' => true],
//            'question4'					 => ['type' => 'text', 'null' => true],
//            'question5'					 => ['type' => 'text', 'null' => true],
//            'question6'					 => ['type' => 'text', 'null' => true],
//            'question7'					 => ['type' => 'text', 'null' => true],
//            'question8'					 => ['type' => 'text', 'null' => true],
//            'question9'					 => ['type' => 'text', 'null' => true],
//            'question10'				 => ['type' => 'text', 'null' => true],
//            'question11'				 => ['type' => 'text', 'null' => true],
//            'question12'				 => ['type' => 'text', 'null' => true],
//            'question13'				 => ['type' => 'text', 'null' => true],
//            'question14'				 => ['type' => 'text', 'null' => true],
//            'question15'				 => ['type' => 'text', 'null' => true],
//            'question16'				 => ['type' => 'text', 'null' => true],
//            'question17'				 => ['type' => 'text', 'null' => true],
//            'question18'				 => ['type' => 'text', 'null' => true],
//            'question19'				 => ['type' => 'text', 'null' => true],
//            'question20'				 => ['type' => 'text', 'null' => true],
//            'question21'				 => ['type' => 'text', 'null' => true],
//            'question22'				 => ['type' => 'text', 'null' => true],
//            'question23'				 => ['type' => 'text', 'null' => true],
//            'question24'				 => ['type' => 'text', 'null' => true],
//        ],
//        'customer_locations'	 => [
//            'id'			 => ['type' => 'bigint', 'auto_increment' => true, 'unsigned' => true],
//            'created_at'	 => ['type' => 'datetime', 'null' => true],
//            'updated_at'	 => ['type' => 'datetime', 'null' => true],
//            'deleted_at'	 => ['type' => 'datetime', 'null' => true],
//            'customer_id'	 => ['type' => 'bigint', 'unsigned' => true, 'null' => true],
//            'latitude'		 => ['type' => 'float'],
//            'longitude'		 => ['type' => 'float'],
//        ],
//        'meal_photos'			 => [
//            'id'				 => ['type' => 'bigint', 'auto_increment' => true, 'unsigned' => true],
//            'created_at'		 => ['type' => 'datetime', 'null' => true],
//            'created_user_id'	 => ['type' => 'int'],
//            'updated_at'		 => ['type' => 'datetime', 'null' => true],
//            'updated_user_id'	 => ['type' => 'int'],
//            'deleted_at'		 => ['type' => 'datetime', 'null' => true],
//            'customer_id'		 => ['type' => 'bigint', 'unsigned' => true],
//            'meal_day'			 => ['type' => 'date'],
//            'meal_timing'		 => ['type' => 'varchar', 'constraint' => 50],
//            'twilio_number'		 => ['type' => 'varchar', 'constraint' => 50],
//            'data'				 => ['type' => 'mediumtext']
//        ],
//        'nutrition_references'	 => [
//            'id'								 => ['type' => 'bigint', 'auto_increment' => true, 'unsigned' => true],
//            'created_at'						 => ['type' => 'datetime', 'null' => true],
//            'updated_at'						 => ['type' => 'datetime', 'null' => true],
//            'deleted_at'						 => ['type' => 'datetime', 'null' => true],
//            'gender'							 => ['type' => 'tinyint', 'unsigned' => true],
//            'physical_activity_level'			 => ['type' => 'tinyint', 'unsigned' => true],
//            'age_category_min'					 => ['type' => 'tinyint', 'unsigned' => true],
//            'age_category_max'					 => ['type' => 'tinyint', 'unsigned' => true],
//            'height'							 => ['type' => 'tinyint', 'unsigned' => true],
//            'energy'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'moisture'							 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'protein'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'lipid'								 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'carbohydrate'						 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'ash'								 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'sodium'							 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'potassium'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'calcium'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'magnesium'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'rin'								 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'iron'								 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'iron_for_menstruation'				 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'zinc'								 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'copper'							 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'manganese'							 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'retinol'							 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'carotene'							 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'beta_carotene'						 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'cryptoxanthin'						 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'beta_carotene_equivalents'			 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'vitamin_A'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'vitamin_D'							 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'alpha_tocopherol'					 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'beta_tocopherol'					 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'gamma_tocopherol'					 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'delta_tocopherol'					 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'tocopherol_equivalents'			 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'vitamin_K'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'vitamin_B1'						 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'vitamin_B2'						 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'niacin'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'vitamin_B6'						 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'vitamin_B12'						 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'folic_acid'						 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'pantothenic_acid'					 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'vitamin_C'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'saturated_fatty_acid'				 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'monovalent_saturated_fatty_acid'	 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'polyvalent_saturated_fatty_acid'	 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'cholesterol'						 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'dietary_fiber_water_soluble'		 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'food_line_insoluble'				 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'dietary_fiber'						 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'salt'								 => ['type' => 'float', 'constraint' => '5,1', 'null' => true],
//            'staple_food_max'					 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'staple_food_min'					 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'side_dish_max'						 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'side_dish_min'						 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'main_dishes_max'					 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'main_dishes_min'					 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'milk_max'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'milk_min'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'fruit_max'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'fruit_min'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'cereal'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'also_attached_much'				 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'sugar_sweeteners_such'				 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'nuts_and_seeds'					 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'green_and_yellow_vegetables'		 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'other_vegetables'					 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'fruits'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'mushrooms'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'seaweed'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'beans'								 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'seafood'							 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'meat'								 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'eggs'								 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'milks'								 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'oils_and_fats'						 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'confectionery'						 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'taste_beverages'					 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'seasonings_and_spices'				 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'protein_category'					 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'mils_category'						 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'green_yellow_vegetables_category'	 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'light_colored_vegetables_cateogry'	 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'cereal_category'					 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//            'oil_category'						 => ['type' => 'smallint', 'unsigned' => true, 'null' => true],
//        ],
	];

	public function up()
	{
		foreach ($this->tables as $name => $fields)
		{
			DBUtil::create_table($name, $fields, ['id']);
		}
	}

	public function down()
	{
		foreach ($this->tables as $name => $fields)
		{
			DBUtil::drop_table($name);
		}
	}

}
